#%RAML 0.8
---
title: SIF Student Locator
version: v3.3.0
mediaType:  application/xml
protocols: [HTTPS]
baseUri: https://sif3service.dev/{version}/svcs/dev/requestProvider/

documentation:
  - title: Overview
    content: |
      The Student Locator service is used to find a specific student in a SIF 3.x system when the refId of the student object is unknown. The primary use case is for use within the SIF Student Record Exchange, where it is used to find a student so that the records of that student can be requested for transfer.

/studentLocatorSearch:
  displayName: Search for a single student
  description: |
    This is a request to a provider to return the targets and IDs for the students within the domain indicated by the identifying elements. The provider returns one Match marked `Valid`, or one or more Matches marked `Ambiguous`, or indicates an error. The results include basic information about the matching student, as well as a set of links to other objects or relevant services. In this way, the Student Locator becomes a starting point for interacting with the student's data elsewhere in the SIF infrastructure.
    
    This action executes a standard SIF *Static Named XQuery*, which must be registered in the zone's Named XQuery Registry with the `xqueryToken` set to `studentLocatorSearch`. This named query template specifies the parameters that can be combined together to execute a potentially complex search for student records. The provider may use these parameters to conduct a probabilistic search with a complex algorithm that tweaks parameters or uses artificial intelligence to deliver the best possible search result. 
    
    All parameters in this search are optional, but consumers should provide as much information as possible to get the best result. 
    
  get:
    description: Submit a search query to the provider
    queryParameters:
      givenName:
        description: The full legal first name given to a person at birth, baptism, or through legal change.
        type: string
        example: John
      middleName:
        description: A full legal middle name given to a person at birth, baptism, or through legal change.
        type: string
        example: Jacob
      familyName:
        description: The full legal last name borne in common by members of a family.
        type: string
        example: Smith
      suffix:
        description: An appendage, if any, used to denote a person's generation in his family (e.g., Jr., Sr., III).
        type: string
        example: Jr.
      birthDate:
        description: The year, month and day on which a person was born, in YYYY-MM-DD format.
        type: date
        example: "1991-04-25"
      sex:
        description: The concept describing the biological traits that distinguish the males and females of a species. 
        type: string
        example: Male
        enum:
          - Male
          - Female
      localId:
        description: A unique number or alphanumeric code assigned to a student by a district or LEA.
        type: string
        maxLength: 40
        example: "120948125"
      stateProvinceId:
        description: A unique number or alphanumeric code assigned to a student by a state.
        type: string
        maxLength: 40
        example: e22cece3-baca-4c88-8485-cef3b869b670
      otherStudentId:
        description: Any other student identifier used to locate a student.
        type: string
      otherStudentIdentificationSystem:
        description: If using the `otherStudentIdentifier`, specify the identification system being used.
        type: string
        enum:
          - CanadianSIN
          - District
          - Family
          - Federal
          - NationalMigrant
          - School
          - SSN
          - State
          - StateMigrant
      organizationId:
        description: The ID of the organization provided above.
        type: string
        example: 013948120948
      organizationIdentificationSystem:
        description: The type of local organization ID to include in the search. For example, school ID or LEA ID.
        type: string
        example: LEA
        enum:
          - School
          - ACT
          - LEA
          - SEA
          - NCES
          - Federal
          - DUNS
          - OtherFederal
          - Other
      stateProvince:
        description: |
          The abbreviation for the state, province or outlying area that assigned the `stateProvinceId`.
        type: string
        enum:
          - AK
          - AL
          - AR
          - AS
          - AZ
          - CA
          - CO
          - CT
          - DC
          - DE
          - FL
          - FM
          - GA
          - GU
          - HI
          - IA
          - ID
          - IL
          - IN
          - KS
          - KY
          - LA
          - MA
          - MD
          - ME
          - MH
          - MI
          - MN
          - MO
          - MP
          - MS
          - MT
          - NC
          - ND
          - NE
          - NH
          - NJ
          - NM
          - NV
          - NY
          - OH
          - OK
          - OR
          - PA
          - PR
          - PW
          - RI
          - SC
          - SD
          - TN
          - TX
          - UT
          - VA
          - VI
          - VT
          - WA
          - WI
          - WV
          - WY
        example: WA
      gradeLevel: 
        description: The current grade or academic level of the student. 
        type: string
        enum: 
          - IT
          - PR
          - PK
          - TK
          - KG
          - 01
          - 02
          - 03
          - 04
          - 05
          - 06
          - 07
          - 08
          - 09
          - 10
          - 11
          - 12
          - 13
          - PS
          - UG
          - Other
        example: "09"
      schoolYear:
        description: The time frame or context that matches the search criteria provided. For example, if you specify gradeLevel, this field is used to match students based on that year. Specify the ending year of the academic year.
        type: integer
        example: "2014"
        minimum: 1950
        maximum: 2049
      projectedGraduationYear:
        description: The year that the student is projected to graduate from high school.
        type: integer
        example: "2016"
        minimum: 1950
        maximum: 2049
      minimumMatchConfidence:
        description: |
          The minimum confidence level that should be used to return matching records, represented by a decimal between `0` and `1`. For example, supplying a value of `0.9` instructs the provider only to return results that have a 90% confident matching record, or a value of `1` ensures that *only* exact matches are returned.
        type: number
        maximum: 1
        minimum: 0
        example: "0.95"
      
    responses:
      200:
        description: Successful search.
        body:
          application/xml:
            example: !include schemas/searchResult.xml
            
/bulkSearch:
  displayName: Search for a group of students
  description: |
    Used for finding large groups of known students e.g., for student recovery (“Where did these 10,000 students end up?”)
    
    *For future use.*